Update the clone method SN-776
saritasa-nest/saritasa-forge-admin pull request #106
Opened 2024-12-25 05:18 UTC by toanphamsaritasa

https://saritasa.atlassian.net/browse/SN-776

2025-01-07 04:45 UTC, vasiliy-chefonov requested changes
<img width="934" alt="image" src="https://github.com/user-attachments/assets/6d1d5ff7-9f58-4af0-9fb5-56282a8a8374" />

I've got an error while updating the Product instance.

2025-01-07 04:45 UTC, vasiliy-chefonov commented on src/Saritasa.NetForge.Blazor/Domain/Extensions/CloneExtensions.cs
> +        var cpType = source is IProxyLazyLoader ? source.GetType().BaseType : source.GetType();
The `Clone` method shouldn't be responsible for checking whether it's an instance of `IProxyLazyLoader`.

2025-01-07 04:45 UTC, vasiliy-chefonov commented on src/Saritasa.NetForge.Blazor/Domain/Extensions/CloneExtensions.cs
> +        var clone = Activator.CreateInstance(cpType);
FIx the warnings, please

2025-01-07 04:45 UTC, vasiliy-chefonov commented on src/Saritasa.NetForge.Blazor/Extensions/ObjectDecorator.cs
> +﻿using Microsoft.EntityFrameworkCore.Metadata.Internal;
Redundant using

2025-01-07 04:45 UTC, vasiliy-chefonov commented on src/Saritasa.NetForge.Blazor/Extensions/ObjectDecorator.cs
> +public class ObjectDecorator
The name of the class doesn't reflect its purpose. I think there is no need to use a decorator pattern here. Can we provide the helper class instead?

2025-01-07 04:45 UTC, vasiliy-chefonov commented on src/Saritasa.NetForge.Blazor/Infrastructure/EfCore/Services/EfCoreDataService.cs
> +using Microsoft.EntityFrameworkCore.Proxies.Internal;
Do we use it?

2025-01-07 04:45 UTC, vasiliy-chefonov commented on src/Saritasa.NetForge.Blazor/Saritasa.NetForge.Blazor.csproj
> +    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="6.0.0" />
Do we really need this one?

2025-01-07 04:45 UTC, vasiliy-chefonov commented on src/Saritasa.NetForge.Blazor/Domain/Extensions/CloneExtensions.cs
> +    public static object? CloneObject(this object? source)
It seems like `CloneJson` is not used anymore. Can we remove it then?

2025-01-08 04:48 UTC, AlexanderMakarov124 commented on src/Saritasa.NetForge.Blazor/Domain/Extensions/CloneExtensions.cs
> +        var cpType = source is IProxyLazyLoader ? source.GetType().BaseType : source.GetType();
What is `cp` in this variable name?

2025-01-08 04:48 UTC, AlexanderMakarov124 commented on src/Saritasa.NetForge.Blazor/Extensions/ObjectDecorator.cs
> +        if (objectType.BaseType != null && objectType.Namespace == "Castle.Proxies")
Can you add more comments what we do here and why?

2025-02-03 03:12 UTC, toanphamsaritasa commented
> <img alt="image" width="934" src="https://private-user-images.githubusercontent.com/81791194/400637080-6d1d5ff7-9f58-4af0-9fb5-56282a8a8374.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzg1NTIwODYsIm5iZiI6MTczODU1MTc4NiwicGF0aCI6Ii84MTc5MTE5NC80MDA2MzcwODAtNmQxZDVmZjctOWY1OC00YWYwLTlmYjUtNTYyODJhOGE4Mzc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjAzVDAzMDMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4ODdiNzFiMjk0N2Y1YTk3ODUzMTA0ZmNhMzhmMzcyZWQ0NDc0NmU4Y2MzOWM4NDVlZmFjMDM4YzUwOTY5NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2rUTEh1W58HEKJ2ZdlJcAcJ-Yi0fHHE2lO-ZnvQ2qu8">
> I've got an error while updating the Product instance.

Could you please show me how to reproduce this issue? I tried with both lazy load/ non-lazy load but still didn't get the error
![image](https://github.com/user-attachments/assets/4b5f0063-e640-4477-bbc3-f8df4ce09ae0)

2025-02-15 10:13 UTC, closed without merging