Feature/SN-438 Implement entity grouping
saritasa-nest/saritasa-forge-admin pull request #11
Opened 2023-11-03 16:48 UTC by toanphamsaritasa

https://saritasa.atlassian.net/browse/SN-438

2023-11-03 16:50 UTC, toanphamsaritasa commented
Grouping feature:
![image](https://github.com/saritasa-nest/saritasa-forge-admin/assets/138420556/9f045ab0-aea8-4e1d-8312-a7562f09e728)

When expanded:
![image](https://github.com/saritasa-nest/saritasa-forge-admin/assets/138420556/86ec9490-e389-4185-b68a-437df12f72d9)


Group description when hover on group name:
![image](https://github.com/saritasa-nest/saritasa-forge-admin/assets/138420556/2e5f343b-a973-4808-af9e-fc5412d836c5)

2023-11-06 08:19 UTC, linhmac approved these changes

2023-11-06 08:19 UTC, linhmac commented on demo/Saritasa.NetForge.Demo.Net7/Infrastructure/DependencyInjection/NetForgeModule.cs
> +                entityOptionsBuilder.SetGroup("Test Name");
About `Test Name -` and `Test Description`, IMHO, I think those are meaningless. Could we change it to `Group Entities -` and `Group Entities - 's description`?

2023-11-06 08:19 UTC, linhmac commented on demo/Saritasa.NetForge.Demo.Net7/Infrastructure/DependencyInjection/NetForgeModule.cs
> +            .ConfigureEntity<ProductTag>(entityOptionsBuilder =>
Why enter at this line? (Example: Line 36 didn't have enter)

2023-11-07 03:50 UTC, vasiliy-chefonov commented
Could you please update the group title font to be bold?

2023-11-07 04:10 UTC, AlexanderMakarov124 commented
Is it fine that on this screenshot `Entity Name` is actually `Group Name`? Is it not confusing?

![image](https://github.com/saritasa-nest/saritasa-forge-admin/assets/45329219/4b6274ec-0e9f-4353-abf3-c9e530b2fa1f)

2023-11-07 04:14 UTC, AlexanderMakarov124 requested changes

2023-11-07 04:14 UTC, AlexanderMakarov124 commented on src/Saritasa.NetForge.DomainServices/Extensions/EntityMetadataExtensions.cs
> +        if (entityGroup != null && !string.IsNullOrEmpty(entityGroup.Name))
What do you think about moving `!string.IsNullOrEmpty(entityGroup.Name)` before searching `entity group`? This can allow us to do less actions when `entityGroup.Name` is `null` or `empty`, it can improve optimization a little
You did something similar when receiving `group name` via `attribute`

2023-11-07 04:14 UTC, AlexanderMakarov124 commented on docs/GROUPING.md
> +To create a new group, utilize the Fluent API. Each group must have a unique name, and a description is optional.
`Each group must have a unique name`
Do we have some validation of uniqueness of the group name?

2023-11-07 04:14 UTC, AlexanderMakarov124 commented on demo/Saritasa.NetForge.Demo.Net7/Models/Product.cs
> -[NetForgeEntity(Description = "The product in the shop.")]
What if user chose some `GroupName`, but there are no `Group` with that name?

2023-11-07 04:23 UTC, vasiliy-chefonov requested changes

2023-11-07 04:23 UTC, vasiliy-chefonov commented on src/Saritasa.NetForge.DomainServices/AdminOptionsBuilder.cs
> +    public AdminOptionsBuilder AddGroup(string name, string description = "")
Maybe we can pass the list of the groups instead?

2023-11-08 08:03 UTC, toanphamsaritasa commented on src/Saritasa.NetForge.Blazor/Controls/Entities.razor.cs
> +        IsInitiallyExpanded = false
Vasily and I have already discussed this. We only have two options: either all groups are initially expanded, or vice versa. Vasily doesn't want a group with too many entities expanded at the start; it would be annoying. So, we decided to make all groups not expand initially.

2023-11-09 03:07 UTC, toanphamsaritasa commented on demo/Saritasa.NetForge.Demo.Net7/Models/Product.cs
> -[NetForgeEntity(Description = "The product in the shop.")]
It will be in the default group, the one group that does not have a name.

2023-11-09 05:02 UTC, toanphamsaritasa commented on src/Saritasa.NetForge.Domain/Entities/Metadata/EntityMetadata.cs
> +    public EntityGroup Group { get; set; } = new();
"I think it should not be nullable. It should be set as a new instance to be in the default group because `MudTable`'s grouping feature requires a group's name to set an entity into a group. So if we set it as null, it will throw an exception since we do not have any value for the group's name (while initializing a new instance for `Group` can guarantee a group with an empty group's name)."

2023-11-09 05:45 UTC, AlexanderMakarov124 commented on demo/Saritasa.NetForge.Demo.Net7/Models/Product.cs
> -[NetForgeEntity(Description = "The product in the shop.")]
Can we set name to the default group? Group with empty string is little strange. For example, `Other` or something

2023-11-09 06:41 UTC, toanphamsaritasa commented on demo/Saritasa.NetForge.Demo.Net7/Models/Product.cs
> -[NetForgeEntity(Description = "The product in the shop.")]
I suggested to Vasily that we change the default group's name to `Other`, but he suggested using an empty group name instead. For example, if no group is specified, there will be only one default group. Having the group's name as `Other` would look very strange.

2023-11-09 07:00 UTC, toanphamsaritasa commented
Update views for grouping:
![image](https://github.com/saritasa-nest/saritasa-forge-admin/assets/138420556/8ae0554a-88b0-44ab-967e-4caa7a707b07)

2023-11-10 03:26 UTC, AlexanderMakarov124 commented
Please, make merges from develop, if there are conflicts with it

2023-11-10 03:38 UTC, AlexanderMakarov124 approved these changes

2023-11-10 03:38 UTC, AlexanderMakarov124 commented on src/Saritasa.NetForge.DomainServices/AdminOptionsBuilder.cs
> +            if (!groupNames.Contains(group.Name))
Why do we need `HashSet` here? Can we use `options.EntityGroupsList` to check for duplicates?

2023-11-10 08:55 UTC, vasiliy-chefonov approved these changes

2023-11-10 08:55 UTC, vasiliy-chefonov commented on README.md
> +        {
Reduce the indentation.

2023-11-10 08:55 UTC, vasiliy-chefonov commented on README.md
> +        {
The same as above

2023-11-10 08:55 UTC, vasiliy-chefonov commented on README.md
> +                new EntityGroup{ Name = "Group Entities 1", Description = "Group Description" },
Can we use some kind of real group names?

2023-11-10 08:55 UTC, vasiliy-chefonov commented on demo/Saritasa.NetForge.Demo.Net7/Infrastructure/DependencyInjection/NetForgeModule.cs
> +                new EntityGroup{ Name = "Group Entities 1", Description = "Group Description" },
Use real group names and descriptions

2023-11-10 08:55 UTC, vasiliy-chefonov commented on src/Saritasa.NetForge.DomainServices/Extensions/EntityMetadataExtensions.cs
> +            var entityGroup =
Duplicated code. Can we move this logic to a separate method?

2023-11-11 07:23 UTC, merged