Add "view site" link to admin panel SN-440
saritasa-nest/saritasa-forge-admin pull request #16
Opened 2023-11-13 11:20 UTC by toanphamsaritasa

https://saritasa.atlassian.net/browse/SN-440

2023-11-13 11:21 UTC, toanphamsaritasa commented
![image](https://github.com/saritasa-nest/saritasa-forge-admin/assets/138420556/5a820e45-0c48-49be-8758-1a775d97baa7)

2023-11-14 03:30 UTC, AlexanderMakarov124 approved these changes

2023-11-15 11:59 UTC, vasiliy-chefonov requested changes
Update the README.md as well, please.

2023-11-15 11:59 UTC, vasiliy-chefonov commented on README.md
> +    optionsBuilder.ConfigureUrl("https://stackoverflow.com/");
Can you replace it with www.example.com?

2023-11-15 11:59 UTC, vasiliy-chefonov commented on src/Saritasa.NetForge.Blazor/Shared/MainLayout.razor
> +        @if (!string.IsNullOrEmpty(AdminOptions.ConfigurableUrl))
Can we just make the default value for your ConfigurableUrl to be "/"?

2023-11-16 08:21 UTC, vasiliy-chefonov approved these changes

2023-11-16 08:21 UTC, vasiliy-chefonov commented on README.md
> +## External link
It's supposed to redirect to the website itself. I'm not sure we should call it External link. Actually, the admin panel is hosted within the main website so it's not an external one.

Call it `View Site URL`

2023-11-16 08:21 UTC, vasiliy-chefonov commented on README.md
> +Located in the top right corner of the admin panel is a "View Site" link, configurable to direct users to an external website.
```suggestion
Located in the top right corner of the admin panel is a "View Site" link, configurable to direct users to the website URL.
```

2023-11-16 08:21 UTC, vasiliy-chefonov commented on README.md
> +The link supports two types of URLs: full paths, e.g., "https://www.example.com/", and relative routes, such as "/index".
```suggestion
The default URL is "/".
```

2023-11-16 08:21 UTC, vasiliy-chefonov commented on README.md
> +If left unconfigured, the link will default to opening the home page of the application.
```suggestion
You can customize this value using the Fluent API:
```

2023-11-16 08:21 UTC, vasiliy-chefonov commented on src/Saritasa.NetForge.DomainServices/AdminOptionsBuilder.cs
> +        if (IsUrlValid(url))
Let's raise the exception in case the URL is invalid.

2023-11-16 08:21 UTC, vasiliy-chefonov commented on src/Saritasa.NetForge.DomainServices/AdminOptionsBuilder.cs
> +        const string pattern =
Can we use [IsWellFormedUriString](https://learn.microsoft.com/en-us/dotnet/api/system.uri.iswellformeduristring?view=net-8.0&redirectedfrom=MSDN#System_Uri_IsWellFormedUriString_System_String_System_UriKind_) with `RelativeOrAbsolute` arg?

2023-11-16 09:25 UTC, merged