Add blazor authorize router view SN-432
saritasa-nest/saritasa-forge-admin pull request #18
Opened 2023-11-20 06:12 UTC by hieu-nguyentan

- Task: https://saritasa.atlassian.net/browse/SN-432

I added a login feature to the demo app to test authorization for the admin panel, possibly showcasing the authentication and authorization functions. I'm unsure whether we should keep it or remove it.

FYI: Login page
![CleanShot 2023-11-20 at 13 10 21](https://github.com/saritasa-nest/saritasa-forge-admin/assets/138435614/33666b8f-ff7d-42cd-8a01-d6365647377f)

2023-11-20 10:00 UTC, AlexanderMakarov124 requested changes
Do we need to update `README.md` with these changes?

2023-11-20 10:00 UTC, AlexanderMakarov124 commented on demo/Saritasa.NetForge.Demo.Net7/ViewModels/LoginViewModel.cs
> +    required public string Password { get; set; }
`public required`?

2023-11-20 10:00 UTC, AlexanderMakarov124 commented on demo/Saritasa.NetForge.Demo.Net7/Infrastructure/DependencyInjection/NetForgeModule.cs
> +            // optionsBuilder.AddAccessRoles("admin", "hieu");
Remove comment

2023-11-20 10:00 UTC, AlexanderMakarov124 commented on demo/Saritasa.NetForge.Demo.Net7/Infrastructure/DependencyInjection/NetForgeModule.cs
> +                return true;
Can we provide example of custom auth function?

2023-11-20 10:00 UTC, AlexanderMakarov124 commented on demo/Saritasa.NetForge.Demo.Net7/Views/Home/Index.cshtml
> +    </style>
Please use separate css file for styles

2023-11-20 10:00 UTC, AlexanderMakarov124 commented on demo/Saritasa.NetForge.Demo.Net7/Views/Home/Index.cshtml
> +                ;
Move semicolon

2023-11-20 10:00 UTC, AlexanderMakarov124 commented on demo/Saritasa.NetForge.Demo.Net7/Views/Home/Index.cshtml
> +                        @Html.TextBoxFor(e => e.Username, "", new { @class = "form-control is-invalid", @placeholder = "Username" })
Use `string.Empty` for empty strings, fix it everywhere

2023-11-20 10:00 UTC, AlexanderMakarov124 commented on demo/Saritasa.NetForge.Demo.Net7/Views/Home/Index.cshtml
> +                        @Html.TextBoxFor(e => e.Username, "", new { @class = "form-control", @placeholder = "Username" })
You have the same string `"Username"` in 2 places, move it to constant

2023-11-20 10:00 UTC, AlexanderMakarov124 commented on demo/Saritasa.NetForge.Demo.Net7/Views/Home/Index.cshtml
> +                        @Html.PasswordFor(e => e.Password, new { @class = "form-control", @placeholder = "Password" })
The same with `"Password"`

2023-11-20 10:00 UTC, AlexanderMakarov124 commented on demo/Saritasa.NetForge.Demo.Net7/Views/Home/Index.cshtml
> +                        @Html.TextBoxFor(e => e.Username, "", new { @class = "form-control is-invalid", @placeholder = "Username" })
Can `@placeholder` be just `placeholder`?

2023-11-20 10:00 UTC, AlexanderMakarov124 commented on src/Saritasa.NetForge.Blazor/App.razor
> +                <p>Only visible while authentication is in progress.</p>
I think `<p>Only visible while authentication is in progress.</p>` should not be here

2023-11-20 10:00 UTC, AlexanderMakarov124 commented on src/Saritasa.NetForge.Blazor/App.razor
> +                <p>You may need to log in as a different user.</p>
This message also looks strange, do we need it?

2023-11-20 10:00 UTC, AlexanderMakarov124 commented on src/Saritasa.NetForge.Blazor/Pages/Index.razor
> +@attribute [Authorize(Policy = "AdminPanelAccess")]
I saw using `"AdminPanelAccess"` at least 2 times, move it to constant

2023-11-20 10:00 UTC, AlexanderMakarov124 commented on src/Saritasa.NetForge.DomainServices/AdminOptionsBuilder.cs
> +    /// <returns></returns>
Remove empty `returns`

2023-11-20 10:03 UTC, AlexanderMakarov124 commented
Is it fine, that I can access admin panel without logging in?

2023-11-24 08:21 UTC, hieu-nguyentan commented on src/Saritasa.NetForge.Blazor/App.razor
> +                <p>You may need to log in as a different user.</p>
The message is displayed to the user when they cannot access the admin panel. We can remove it, but it may cause a little confusion for the user because no error is shown when not authorized

2023-11-24 08:23 UTC, AlexanderMakarov124 commented on src/Saritasa.NetForge.Blazor/App.razor
> +                <p>You may need to log in as a different user.</p>
I meant only this part `<p>You may need to log in as a different user.</p>`

2023-11-28 02:43 UTC, hieu-nguyentan commented
@AlexanderMakarov124 I just updated. By default, if we don't set any rules (roles or custom check function), anybody can access the admin panel.

2023-11-28 04:51 UTC, AlexanderMakarov124 approved these changes

2023-11-28 04:51 UTC, AlexanderMakarov124 commented on demo/Saritasa.NetForge.Demo.Net7/Views/Home/Index.cshtml
> +
Remove one line

2023-11-28 04:51 UTC, AlexanderMakarov124 commented on demo/Saritasa.NetForge.Demo.Net7/Views/Home/Index.cshtml
> +                    @if (ViewData.ModelState.GetFieldValidationState("Username") == ModelValidationState.Invalid)
Replace `"Username"` with constant too

2023-11-28 04:51 UTC, AlexanderMakarov124 commented on demo/Saritasa.NetForge.Demo.Net7/Views/Home/Index.cshtml
> +                    @if (ViewData.ModelState.GetFieldValidationState("Password") == ModelValidationState.Invalid)
The same with password

2023-11-28 04:51 UTC, AlexanderMakarov124 commented on src/Saritasa.NetForge.Blazor/Constants/PolicyConstant.cs
> +public static class PolicyConstant
```suggestion
public static class PolicyConstants
```

2023-11-28 04:51 UTC, AlexanderMakarov124 commented on README.md
> +
Why do we need this change? Try not to change things, that unrelated to your task

2023-11-28 04:51 UTC, AlexanderMakarov124 commented on README.md
> +
Same

2023-11-28 04:51 UTC, AlexanderMakarov124 commented on README.md
> +```
Same

2023-11-29 04:33 UTC, vasiliy-chefonov commented
@hieu-nguyentan Please, resolve possible conflicts with dev.

2023-11-29 05:06 UTC, vasiliy-chefonov commented
> @AlexanderMakarov124 I just updated. By default, if we don't set any rules (roles or custom check function), anybody can access the admin panel (include anonymous).

Could you please update the demo to allow access to authorized users only? All roles are allowed.

2023-11-29 05:06 UTC, vasiliy-chefonov approved these changes

2023-11-29 06:49 UTC, hieu-nguyentan commented on src/Saritasa.NetForge.Blazor/Infrastructure/Authentication/CustomAuthFunctionHandler.cs
> +    protected override async Task HandleRequirementAsync(AuthorizationHandlerContext context,
We cannot do that; it doesn't support it.

2023-11-29 06:54 UTC, hieu-nguyentan commented on README.md
> +        return true; // Return true if the access is granted, otherwise return false
I have the `async` keyword in the signature of the lambda function, so I don't think we should return `Task.FromResult(...)`

What do you think?

2023-11-29 08:04 UTC, merged