SN-441 add breadcrumbs to entity details page
saritasa-nest/saritasa-forge-admin pull request #19
Opened 2023-11-20 09:30 UTC by toanphamsaritasa

https://saritasa.atlassian.net/browse/SN-441

2023-11-20 09:33 UTC, toanphamsaritasa commented
When go to entity detail page, there is a breadcrumbs navigation
![image](https://github.com/saritasa-nest/saritasa-forge-admin/assets/138420556/3953bf08-e7e9-4fb0-ba66-048daba00160)
Clicking on "Entities" will redirect to entities page.
![image](https://github.com/saritasa-nest/saritasa-forge-admin/assets/138420556/37fac3ca-7bb0-44ae-84e1-214e1f03fdd2)
Clicking on "Home" will redirect to homepage of web application.

2023-11-20 10:14 UTC, AlexanderMakarov124 approved these changes

2023-11-23 04:09 UTC, vasiliy-chefonov requested changes

2023-11-23 04:09 UTC, vasiliy-chefonov commented on src/Saritasa.NetForge.Blazor/Pages/EntityDetails.razor.cs
> +        new BreadcrumbItem("Entities", href: "/admin"),
It shouldn't be hardcoded. Users can actually set the custom value for that using the `UseEndpoint` from the `AdminOptionsBuilder`.

2023-11-23 04:09 UTC, vasiliy-chefonov commented on src/Saritasa.NetForge.Blazor/Pages/EntityDetails.razor.cs
> +        new BreadcrumbItem("Home", href: "/"),
Let's leave only the Entities, no Home. View Site link is enough for the main page navigation I guess.

2023-11-23 04:09 UTC, vasiliy-chefonov commented on src/Saritasa.NetForge.Blazor/Pages/EntityDetails.razor.cs
> +    protected override void OnParametersSet()
Can we override `OnInitializedComponentAsync`?

2023-11-23 04:09 UTC, vasiliy-chefonov commented on src/Saritasa.NetForge.Blazor/Pages/EntityDetails.razor.cs
> +        entityDetailsViewModel = ViewModelFactory.Create<EntityDetailsViewModel>(StringId);
what is the purpose of this change? Can we just use `this.ViewModel`?

2023-11-23 07:14 UTC, toanphamsaritasa commented on src/Saritasa.NetForge.Blazor/Pages/EntityDetails.razor.cs
> +    protected override void OnParametersSet()
From the document of [ComponentBase.OnInitializedAsync](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.componentbase.oninitializedasync?view=aspnetcore-7.0) indicates that

> Method invoked when the component is ready to start, having received its initial parameters from its parent in the render tree.

While in this method, we need to get the parameter and put it into the list for the breadcrumbs before initialize the ` MudBreadcrumbs` component. Therefore, I think it's better to use `OnParametersSet`. Also, I tried to replace it with `OnInitializedComponentAsync` and the breadcrumbs navigation is not working properly.

2023-11-24 07:02 UTC, vasiliy-chefonov approved these changes

2023-11-24 07:48 UTC, merged