Feature/sn 422 server side search for entity fields
saritasa-nest/saritasa-forge-admin pull request #5
Opened 2023-10-30 03:44 UTC by AlexanderMakarov124

2023-10-30 14:03 UTC, vasiliy-chefonov commented
Update the readme as well

2023-10-30 14:07 UTC, vasiliy-chefonov requested changes

2023-11-01 12:22 UTC, vasiliy-chefonov approved these changes

2023-11-01 12:22 UTC, vasiliy-chefonov commented on docs/SEARCH.md
> +    * Starts With Case Sensitive;
Can we provide the examples of the SQL queries for each type?

2023-11-01 12:22 UTC, vasiliy-chefonov commented on src/Saritasa.NetForge.Infrastructure.EfCore/Services/EfCoreDataService.cs
> +        // entity => Regex.IsMatch(((entityType)entity).propertyName, searchWord, RegexOptions.IgnoreCase)
Should we use `GetConvertedExpressionWhenPropertyIsNotString` here as well?

2023-11-02 07:33 UTC, toanphamsaritasa approved these changes

2023-11-02 07:33 UTC, toanphamsaritasa commented on docs/SEARCH.md
> +Every word in the input will become separate search entry. Phrases between quoutes: `"` or `'` will also become separate entries.
```suggestion
Every word in the input will become separate search entry. Phrases between quotes: `"` or `'` will also become separate entries.
```

2023-11-02 08:06 UTC, merged