Add validate when create or edit entity SN-561
saritasa-nest/saritasa-forge-admin pull request #70
Opened 2024-04-22 09:54 UTC by tanhieu-nguyen

https://saritasa.atlassian.net/browse/SN-561

2024-04-23 11:22 UTC, AlexanderMakarov124 requested changes
Can you put data validation attributes to our demo models?

2024-04-23 11:22 UTC, AlexanderMakarov124 commented on src/Saritasa.NetForge.Tests/EntityServiceTests/ValidateEntityTests.cs
> +        Assert.All(new List<string> { propertyName, "required" }, item => Assert.Contains(item, requireError.ErrorMessage));
It is not obvious what exactly failed when test failed when test has many asserts

2024-04-23 11:22 UTC, AlexanderMakarov124 commented on src/Saritasa.NetForge.Tests/EntityServiceTests/ValidateEntityTests.cs
> +        Assert.All(new List<string> { propertyName, "maximum length", maxLengthValue.ToString() }, item => Assert.Contains(item, maxLengthError.ErrorMessage));
The same

2024-04-23 11:22 UTC, AlexanderMakarov124 commented on src/Saritasa.NetForge.Tests/EntityServiceTests/ValidateEntityTests.cs
> +        var instance = new Dummy
You could add phone property to the existing entity, for example for `ContactInfo`, instead of creating `Dummy`

2024-04-25 02:36 UTC, tanhieu-nguyen commented on src/Saritasa.NetForge.Mvvm/ViewModels/CreateEntity/CreateEntityViewModel.cs
> +    public List<ComponentErrorModel> ErrorViewModels { get; } = [];
So it relates to the style of code. When I initialize a member by `public List<ComponentErrorModel> ErrorViewModels { get; } = new();` it says that I can simplify it more by using collection expressions. 
The warning `Opening Square Brackets Must Be Spaced Correctly` may apply to the index operator, and the rule for collection expressions is not included. 
So should we use the new operator or collection expressions? What do you think?

2024-04-25 02:39 UTC, tanhieu-nguyen commented on src/Saritasa.NetForge.Mvvm/ViewModels/CreateEntity/CreateEntityViewModel.cs
> +            ErrorViewModels.ForEach(e => e.ErrorMessage = string.Empty);
I think maybe not; it will clear the errors generated by previous validation and will need to be cleared again if revalidating. 
I will add a comment to make it clearer.

2024-04-25 02:40 UTC, tanhieu-nguyen commented on src/Saritasa.NetForge.Mvvm/ViewModels/CreateEntity/CreateEntityViewModel.cs
> +        var error = new List<ValidationResult>();
think there might be an error because if there are no errors, there won't be any validation results

2024-04-25 02:43 UTC, tanhieu-nguyen commented on src/Saritasa.NetForge.Mvvm/ViewModels/EditEntity/EditEntityViewModel.cs
> +    public List<ComponentErrorModel> ErrorViewModels { get; } = [];
The same applies to the warning in `CreateEntityViewModel.cs`, so I will wait for the discussion mentioned earlier

2024-04-25 02:52 UTC, tanhieu-nguyen commented on src/Saritasa.NetForge.Tests/PhoneMaskAttribute.cs
> +            if (maskPattern[i] == '-' && phoneNumber[i] != '-')
So it only for the testing purpose, the custom validation, i think it dont need to have seperate consts
Also, I believe leaving it for readability
So how do you think?

2024-04-25 03:11 UTC, tanhieu-nguyen commented
@AlexanderMakarov124 
In validation unit tests, more assertions are needed to validate both the result and the errors produced by the validation process. Perhaps adding more comments to the code or changing the failure message when a unit test fails could help (this approach might not be perfect because the Assert related to collections does not provide a way to override the message)
How do you think?

2024-04-25 08:06 UTC, AlexanderMakarov124 commented on src/Saritasa.NetForge.Mvvm/ViewModels/CreateEntity/CreateEntityViewModel.cs
> +    public List<ComponentErrorModel> ErrorViewModels { get; } = [];
It's fine for me to use collection expressions. Can you update `StyleCop` package? It looks like, this was fixed in new version

2024-04-25 08:18 UTC, AlexanderMakarov124 commented on src/Saritasa.NetForge.Tests/PhoneMaskAttribute.cs
> +            if (maskPattern[i] == '-' && phoneNumber[i] != '-')
It may be not obvious what means `d`, but for example with constant `const char digit = 'd'` it will be clearer
Also, when you have something that repeats several times, it's good practice to use constants

2024-04-25 08:44 UTC, AlexanderMakarov124 commented
> @AlexanderMakarov124 In validation unit tests, more assertions are needed to validate both the result and the errors produced by the validation process. Perhaps adding more comments to the code or changing the failure message when a unit test fails could help (this approach might not be perfect because the Assert related to collections does not provide a way to override the message) How do you think?

I'm not sure that we need to test errors in this case
@vasiliy-chefonov What do you think?

2024-05-05 11:37 UTC, vasiliy-chefonov reviewed
As for the tests. Can we just update the Domain classes with attributes and validations? Why do we need to dynamically extend the Dummy class?

2024-05-05 11:37 UTC, vasiliy-chefonov commented on src/Saritasa.NetForge.Mvvm/ViewModels/EditEntity/EditEntityViewModel.cs
> +        var error = new List<ValidationResult>();
Can we avoid the code duplication in `CreateEntityViewModel` & `EditEntityViewModel`? I guess we can provide a base view model class for them. What do you think?

2024-05-05 11:37 UTC, vasiliy-chefonov commented on src/Saritasa.NetForge.Tests/EntityServiceTests/ValidateEntityTests.cs
> +using Saritasa.NetForge.Tests.Domain.Models;
Not used

2024-05-06 02:59 UTC, tanhieu-nguyen commented on src/Saritasa.NetForge.Blazor/Pages/EditEntity.razor
> +                            componentError = new ComponentErrorModel
No, i create the `FieldErrorModels` in code behind in `CreateEntityViewModel CreateViewModel()` but the property of model is empty, so only way to do is create in razor file.

2024-05-06 03:04 UTC, tanhieu-nguyen commented on src/Saritasa.NetForge.Mvvm/ViewModels/EditEntity/EditEntityViewModel.cs
> +        var error = new List<ValidationResult>();
i think the base model is using for all the view model in this application, so maybe we have the view model that unused the method

2024-05-06 03:09 UTC, tanhieu-nguyen commented
> As for the tests. Can we just update the Domain classes with attributes and validations? Why do we need to dynamically extend the Dummy class?

So i create the dummy class for dynamic create the validation attribute, so if not use the dynamiclly extend i think we may have 3 seperate doimain class for that validate (one have 1 property and have 1 attribute for it (SinglePropertySingleValidate), one have 2 properties and each have 1 attribute for it (SinglePropertyMultipleValidate), one have 2 properties and each have 2 attribute for it (MultiplePropertyMultipleValidate))

2024-05-24 11:53 UTC, vasiliy-chefonov commented on src/Saritasa.NetForge.Mvvm/ViewModels/EditEntity/EditEntityViewModel.cs
> +        var error = new List<ValidationResult>();
So we can provide a base class for CreateEntityViewModel & EditEntityViewModel that will be inherited from `BaseViewModel`

2024-05-24 11:53 UTC, vasiliy-chefonov commented
@tanhieu-nguyen Any progress on this PR?

2024-05-24 11:55 UTC, tanhieu-nguyen commented
Yes, I am updating the test case for the unit test

2024-05-30 06:25 UTC, AlexanderMakarov124 approved these changes
Don't forget to resolve unresolved comments

2024-05-30 06:25 UTC, AlexanderMakarov124 commented on src/Saritasa.NetForge.Tests/PhoneMaskAttribute.cs
> +    /// Constructor
```suggestion
    /// Constructor.
```

2024-05-30 06:25 UTC, AlexanderMakarov124 commented on src/Saritasa.NetForge.Blazor/Pages/CreateEntity.razor
> +
Can we move this to ViewModel?

2024-05-30 06:25 UTC, AlexanderMakarov124 commented on src/Saritasa.NetForge.Blazor/Pages/EditEntity.razor
> +
Same

2024-05-30 06:25 UTC, AlexanderMakarov124 commented on src/Saritasa.NetForge.Tests/PhoneMaskAttribute.cs
> +/// <b>Note:</b> It only use for the test custom validation only, not using on anywhere.
This is not relevant anymore?

2024-05-30 06:25 UTC, AlexanderMakarov124 commented on src/Saritasa.NetForge.Tests/PhoneMaskAttribute.cs
> +        var phoneNumber = (string)value;
`ToString`?

2024-05-30 06:25 UTC, AlexanderMakarov124 commented on src/Saritasa.NetForge.UseCases/Services/EntityService.cs
> +        return Validator.TryValidateObject(instance, context, errors, true);
Prefer specifying parameter name for `null` and `bool`
```suggestion
        var context = new ValidationContext(instance, serviceProvider, items: null);

        return Validator.TryValidateObject(instance, context, errors, validateAllProperties: true);
```

2024-05-31 07:36 UTC, tanhieu-nguyen commented on src/Saritasa.NetForge.Blazor/Pages/CreateEntity.razor
> +
No, i create the `FieldErrorModels` in code behind in `CreateEntityViewModel CreateViewModel()` but the property of model is empty, so only way to do is create in razor file.

2024-05-31 07:37 UTC, tanhieu-nguyen commented on src/Saritasa.NetForge.Tests/PhoneMaskAttribute.cs
> +/// <b>Note:</b> It only use for the test custom validation only, not using on anywhere.
I think it still relevant, so it only use for custom attribute valiation in unit test

2024-05-31 07:42 UTC, tanhieu-nguyen commented on src/Saritasa.NetForge.Mvvm/ViewModels/EditEntity/EditEntityViewModel.cs
> +        var error = new List<ValidationResult>();
I think i will write the helper method

2024-06-03 04:22 UTC, vasiliy-chefonov commented on src/Saritasa.NetForge.Blazor/Pages/CreateEntity.razor
> +                        if (ViewModel.FieldErrorModels.Count != ViewModel.Model.Properties.Count)
Move this logic to the view model, please. Discussed offline.

2024-06-13 05:47 UTC, vasiliy-chefonov approved these changes

2024-06-13 16:57 UTC, merged