Display general error message when have exception SN-712
saritasa-nest/saritasa-forge-admin pull request #79
Opened 2024-09-08 01:24 UTC by tanhieu-nguyen

https://saritasa.atlassian.net/browse/SN-712

2024-09-09 04:10 UTC, AlexanderMakarov124 requested changes
1. Please add screenshots to see how it looks
2. Do we need to handle exceptions when we remove entity?

2024-09-09 04:10 UTC, AlexanderMakarov124 commented on src/Saritasa.NetForge.Infrastructure.EfCore/Services/EfCoreDataService.cs
> +            dbContext.ChangeTracker.Clear();
Please add comment why we need this

2024-09-09 04:10 UTC, AlexanderMakarov124 commented on src/Saritasa.NetForge.Mvvm/ViewModels/EditEntity/EditEntityViewModel.cs
>      }
Please fix warning on this line

2024-09-09 04:10 UTC, AlexanderMakarov124 commented on src/Saritasa.NetForge.Mvvm/ViewModels/ValidationEntityViewModel.cs
> +    public string GeneralError { get; set; } = "";
`string.Empty`?

2024-09-18 06:40 UTC, tanhieu-nguyen commented
Create entity or edit entity:
- ![image](https://github.com/user-attachments/assets/7ef65554-b6c5-4b1d-801e-a9975dfc3d84)

Delete entity:
- ![image](https://github.com/user-attachments/assets/7201b1c8-bf21-44f1-b6ae-443e0ebd44e0)

2024-09-21 15:48 UTC, toanphamsaritasa commented
Can we have similar style when displaying exceptions for create, update and delete? Create or edit is using MudAlert and delete is using Snackbar is just strange. Can we just use MudAlert or Snackbar for all of these operations?

2024-09-23 04:02 UTC, AlexanderMakarov124 commented
> Can we have similar style when displaying exceptions for create, update and delete? Create or edit is using MudAlert and delete is using Snackbar is just strange. Can we just use MudAlert or Snackbar for all of these operations?

To choose between `MudAlert` and `Snackbar` I prefer to use `MudAlert` because `Snackbar` is hiding after some time.

2024-09-24 06:01 UTC, tanhieu-nguyen commented
Updated:
Create entity or edit entity:

![image](https://github.com/user-attachments/assets/7a2d9276-1b96-4f44-af1e-61e6c1e02a84)

2024-09-26 06:37 UTC, vasiliy-chefonov approved these changes

2024-10-02 03:48 UTC, toanphamsaritasa approved these changes
Please resolve the conflicts

2024-10-09 07:00 UTC, merged