Add Excluding configs SN-748
saritasa-nest/saritasa-forge-admin pull request #89
Opened 2024-10-04 05:53 UTC by vasiliy-chefonov

https://saritasa.atlassian.net/browse/SN-748

Now we can exclude all properties from the entity and include only specific ones. The configuration is applicable for both ordinary and navigation properties.

The properties will be excluded from the list view and details page.

2024-10-04 08:35 UTC, AlexanderMakarov124 requested changes

2024-10-04 08:35 UTC, AlexanderMakarov124 commented on README.md
> +## Exclude All Properties and Include Specific Only
Don't forget to update `Table of content` at the start of `README.md`

2024-10-04 08:35 UTC, AlexanderMakarov124 commented on src/Saritasa.NetForge.Mvvm/ViewModels/EntityDetails/EntityDetailsViewModel.cs
> +            CanAdd = Model is { CanAdd: true, IsKeyless: false } && Model.Properties.Any();
What do think about displaying some `This entity doesn't have configured properties to display` message instead of hiding buttons on list view page when `Model.Properties.Any()` is `false`?

2024-10-04 08:35 UTC, AlexanderMakarov124 commented on src/Saritasa.NetForge.Domain/Entities/Options/EntityOptions.cs
> +    public bool ExcludeAllProperties { get; set; }
Can we just mark all properties as hidden? So we just reuse our hide property behavior.
For example, we can't use not included properties in calculated properties with this approach

2024-10-04 14:23 UTC, vasiliy-chefonov commented on src/Saritasa.NetForge.Domain/Entities/Options/EntityOptions.cs
> +    public bool ExcludeAllProperties { get; set; }
I think the number of calculated properties is usually not large.
But at the same time hiding from displaying is not the same as excluding from query. This method excludes everywhere.

2024-10-07 03:19 UTC, AlexanderMakarov124 approved these changes

2024-10-07 03:19 UTC, AlexanderMakarov124 commented on src/Saritasa.NetForge.Blazor/Pages/EntityDetails.razor
> +        @if (!ViewModel.HasProperties)
Can we make this condition more outer? Something similar to `@if (ViewModel.IsEntityExists)` condition.
Reason for this is we don't need `Add`, `Delete` and `SearchInput` when there are no properties

2024-10-07 08:32 UTC, vasiliy-chefonov commented on src/Saritasa.NetForge.Blazor/Pages/EntityDetails.razor
> +        @if (!ViewModel.HasProperties)
I reused the existing properties: `CanAdd`, `CanDelete`, `CanEdit`.

2024-10-07 08:50 UTC, vasiliy-chefonov commented on src/Saritasa.NetForge.Blazor/Pages/EntityDetails.razor
> +        @if (!ViewModel.HasProperties)
Discussed offline

2024-10-07 08:53 UTC, merged